### ISSUE TITLE
CTFAK2.0 is not decompiling.

### ISSUE THREAD

**Issue by MMFan4315** [CTFAK/CTFAK2.0#101]
(this is all i could copy before it crashed)
bCodec.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.ZlibStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.ZlibBaseStream.UncompressBuffer(Byte[] compressed, Stream decompressor)
   at Ionic.Zlib.ZlibStream.UncompressBuffer(Byte[] compressed)
   at CTFAK.Memory.Decompressor.DecompressBlock(ByteReader reader, Int32 size) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\Memory\Decompression.cs:line 45
   at CTFAK.Memory.Decryption.DecodeMode3(Byte[] chunkData, Int32 chunkId, Int32& decompressed) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\Memory\Decryption.cs:line 79
   at CTFAK.CCN.Chunks.Chunk.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Chunk.cs:line 42
   at CTFAK.CCN.GameData.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\GameData.cs:line 108
   at CTFAK.FileReaders.ExeFileReader.LoadGame(String gamePath) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\EXE\ExeFileReader.cs:line 98
   at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 180

**Comment by AITYunivers** [comment]
Try [UnEx](https://github.com/AITYunivers/CTFAK-UnEx/actions/runs/8941287210)
