### ISSUE TITLE
zlibwapi error

### ISSUE THREAD

**Issue by Brazilocus** [CTFAK/CTFAK2.0#110]
So, I initially decided that it would be best to not create a github account and do it manually instead. However, when i did that, i got this error:
System.DllNotFoundException
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'x64\zlibwapi.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at Joveler.DynLoader.NetSafeLibHandle..ctor(String libPath)
   at Joveler.DynLoader.DynLoaderBase.LoadLibrary(String libPath)
   at Joveler.DynLoader.LoadManagerBase`1.GlobalInit(String libPath)
   at Joveler.Compression.ZLib.ZLibInit.GlobalInit(String libPath)
   at CTFAK.CTFAKCore.Init() in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CTFAKCore.cs:line 27
   at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 29

I also tried creating a github account and doing it the recommended way instead, but the error persists.

**Comment by AITYunivers** [comment]
Extract ctfakrequirements.zip as stated in the readme man.

**Comment by Brazilocus** [comment]
Well, i don't think i understand it correctly. In the readme.md file, it says "extract ctfakrequirements.zip into the same folder it's found in.", so i did it like this:
![Capture](https://github.com/user-attachments/assets/d54b8730-9ec3-4717-8423-3c663d55d22e)
However, i also tried putting in the "Plugins" folder, and to no luck.

**Comment by AITYunivers** [comment]
You're not very smart, are you?

> To know you've extracted it properly, template.mfa should be found in the same folder as CTFAK.Cli.exe.

Doesn't mean "Move template.mfa"

**Comment by Brazilocus** [comment]
Does it mean keep in the "ctfakrequirements" folder? If that's the case, the error still is there.

**Comment by AITYunivers** [comment]
No, it means extract it to the folder that contains CTFAK.Cli.exe, obviously.

**Comment by Brazilocus** [comment]
It worked! I'm sorry for wasting your time and not understanding how to follow directions, though.
