### ISSUE TITLE
Unhandled exception. System.IO.EndOfStreamException error

### ISSUE THREAD

**Issue by SonicFNaF** [CTFAK/CTFAK2.0#13]
So basically, I was decompiling the game, and it said "Parameters" and there was no tutorial on this program so I typed something and then it gave me this: Reading game with "Normal EXE"
Unhandled exception. System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt16()
   at CTFAK.Memory.ByteReader.PeekUInt16() in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\ByteReader.cs:line 65
   at CTFAK.FileReaders.ExeFileReader.ReadHeader(ByteReader reader) in E:\repos\CTFAK2.0\Core\CTFAK.Core\EXE\ExeFileReader.cs:line 83
   at CTFAK.FileReaders.ExeFileReader.LoadGame(String gamePath) in E:\repos\CTFAK2.0\Core\CTFAK.Core\EXE\ExeFileReader.cs:line 42
   at Program.Main(String[] args) in E:\repos\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 123. you can please tell how to fix this and also give me a tutorial? Thanks.

**Comment by AITYunivers** [comment]
That's not related to parameters, What game are you trying?

**Comment by SonicFNaF** [comment]
![Screenshot 2022-10-02 07-15-16](https://user-images.githubusercontent.com/94878804/193437545-ffc794dd-b4a6-48e4-9313-fbacefdc7b28.png)

**Comment by SonicFNaF** [comment]
![Screenshot 2022-10-02 07-15-16](https://user-images.githubusercontent.com/94878804/193437545-ffc794dd-b4a6-48e4-9313-fbacefdc7b28.png)

**Comment by SonicFNaF** [comment]
See this the parameters screen, and I have no idea how to continue the decompilation

**Comment by SonicFNaF** [comment]
So there's only Android and Normal EXE option, can you fix that?

**Comment by AITYunivers** [comment]
The game is compiled with Chowdren, CTFAK cannot decompile it.
