### ISSUE TITLE
Unhandled exception, ZlibException: Bad state, on opening non-Unicode game

### ISSUE THREAD

**Issue by 000TragicSolitude** [CTFAK/CTFAK2.0#22]
On trying this with Japanese games, I'm crashing on trying to uncompress the game's exe.

**CTFAK 2.2.0.0
Reading game with "Normal EXE"
28842210
[12:47:28:41] Fusion Build: 288
Unhandled exception. Ionic.Zlib.ZlibException: Bad state (unknown compression method (0x5F))
   at Ionic.Zlib.InflateManager.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibCodec.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.ZlibStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.ZlibBaseStream.UncompressBuffer(Byte[] compressed, Stream decompressor)
   at Ionic.Zlib.ZlibStream.UncompressBuffer(Byte[] compressed)
   at CTFAK.Memory.Decompressor.DecompressBlock(ByteReader reader, Int32 size, Int32 decompSize) in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\Decompression.cs:line 30
   at CTFAK.Memory.Decryption.DecodeMode3(Byte[] chunkData, Int32 chunkSize, Int32 chunkId, Int32& decompressed) in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\Decryption.cs:line 92
   at CTFAK.CCN.Chunks.Chunk.Read() in E:\repos\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Chunk.cs:line 49
   at CTFAK.CCN.GameData.Read(ByteReader reader) in E:\repos\CTFAK2.0\Core\CTFAK.Core\CCN\GameData.cs:line 97
   at CTFAK.FileReaders.ExeFileReader.LoadGame(String gamePath) in E:\repos\CTFAK2.0\Core\CTFAK.Core\EXE\ExeFileReader.cs:line 72
   at Program.Main(String[] args) in E:\repos\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 123**

I'm unsure if it is specifically with Japanese games, but currently on two tests they've crashed at the same step with the same sort of error log.
I've switched to trying this program after failures with a branch of Anaconda giving me issues with translating the Japanese strings/keeping image transparencies. So I may be messing something up, apologies if it's a blunder on my part.
I can provide exes to test on request

**Comment by lily-snow-9** [comment]
if the name, copyright or mfa name has Japanese/Unicode characters - it'll fail as CTFAK does not support key generation for Unicode characters

**Comment by ChadBallsIsBack** [comment]
I HATE NIGGLERS ARGHHHHHH SLAVA UKRAINI #NATO #NATO #NATO
ChadBalls69

**Comment by ChadBallsIsBack** [comment]
كرات تشاد 69
كرات تشاد 69
كرات تشاد 69
كرات تشاد 69
كرات تشاد 69

**Comment by ChadBallsIsBack** [comment]
كرات تشاد 69
كرات تشاد 69
كرات تشاد 69
كرات تشاد 69
كرات تشاد 69

**Comment by ChadBallsIsBack** [comment]
I am Clickteam Copyright Enforcer please take this down and put a hijab on wom*n or we will sue. Slava Ukraini. Not halal.
