### ISSUE TITLE
System.ArgumentOutOfRangeException: Non-negative number required

### ISSUE THREAD

**Issue by RandomGuyHere1234** [CTFAK/CTFAK2.0#31]
![image](https://user-images.githubusercontent.com/120520698/209010922-726ccfc7-c29d-4de0-95f3-80cc40215582.png)
CTFAK 2.2.0.0
Reading game with "Normal EXE"
3683467
[23:01:00:57] Fusion Build: 292
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at CTFAK.Memory.ByteReader.ReadBytes(Int32 count) in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\ByteReader.cs:line 164
   at CTFAK.Memory.Decompressor.DecompressBlock(ByteReader reader, Int32 size, Int32 decompSize) in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\Decompression.cs:line 30
   at CTFAK.Memory.Decryption.DecodeMode3(Byte[] chunkData, Int32 chunkSize, Int32 chunkId, Int32& decompressed) in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\Decryption.cs:line 92
   at CTFAK.CCN.Chunks.Chunk.Read() in E:\repos\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Chunk.cs:line 49
   at CTFAK.CCN.GameData.Read(ByteReader reader) in E:\repos\CTFAK2.0\Core\CTFAK.Core\CCN\GameData.cs:line 97
   at CTFAK.FileReaders.ExeFileReader.LoadGame(String gamePath) in E:\repos\CTFAK2.0\Core\CTFAK.Core\EXE\ExeFileReader.cs:line 72
   at Program.Main(String[] args) in E:\repos\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 123

This never really happened on other Clickteam games so I don't really know why this is happening, cheers.

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
same issue here, windows 10 visual studio 2022

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
Perhaps some different Parameters could help but idk where to look

**Comment by AITYunivers** [comment]
@g-l-i-t-c-h-o-r-s-e Your exe isn't made in Clickteam Fusion 2.5.

**Comment by AITYunivers** [comment]
As for you @RandomGuyHere1234, I can't do much for your without the exe. Reopen this issue with the exe and I'll try to assist you.
