### ISSUE TITLE
(Image Extraction Error) System.ArgumentException: An item with the same key has already been added. Key: 0

### ISSUE THREAD

**Issue by ithinkandicode** [CTFAK/CTFAK2.0#45]
CTFAK crashes for me when I try to extract images. I've had 2 different errors. Here's the first one, which happens if I just run the CCN dumper without parameters:

![image](https://user-images.githubusercontent.com/43499897/233808509-30dbbfa0-bbae-44bb-8e81-8241f0077e9a.png)

```
System.ArgumentOutOfRangeException
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at CTFAK.CCN.Chunks.Banks.Image.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Banks\ImageBank.cs:line 296
   at CTFAK.CCN.Chunks.Banks.ImageBank.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Banks\ImageBank.cs:line 41
   at CTFAK.CCN.GameData.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\GameData.cs:line 365
   at CTFAK.EXE.CCNFileReader.LoadGame(String gamePath) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\FileReaders\CCNFileReader.cs:line 34
   at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 180
```

After that error, I tried again but only dumping the images with the `-onlyimages` parameter (as I only need the images), and it crashed with this error and no progress:

![error](https://user-images.githubusercontent.com/43499897/233808065-dc4823f0-3de4-47ef-a8be-801032793134.png)

```
System.ArgumentException
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at CTFAK.CCN.Chunks.Banks.ImageBank.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Banks\ImageBank.cs:line 43
   at CTFAK.CCN.GameData.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\GameData.cs:line 365
   at CTFAK.EXE.CCNFileReader.LoadGame(String gamePath) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\FileReaders\CCNFileReader.cs:line 34
   at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 180
```

Here's the dat file (525mb):
https://drive.google.com/file/d/1BkuLZxUzCiQfMO7HyFivelvbMDGfnBqB/view?usp=share_link

Any help you can give me is most appreciated! I only want the images so I can add them to the game's wiki 🤗

**Comment by AITYunivers** [comment]
Not accepting issues regarding Decompression, Decryption, or Image Reading currently as they are in the middle of a complete recode. If you need images eagerly, use [Source Explorer](https://github.com/LAK132/SourceExplorer).

**Comment by ithinkandicode** [comment]
Thanks anyway, Source Explorer doesn't work with this game (I raised an issue [here](https://github.com/LAK132/SourceExplorer/issues/109)). Good luck with the recode!
