### ISSUE TITLE
Sonic After the Sequel (Omega Release) + Sonic and the Fallen Star unable to decompile

### ISSUE THREAD

**Issue by SuperSonic472** [CTFAK/CTFAK2.0#48]
SATSO

Specs
EXE Game
Flash files outside of exe
Made in Multiedia Fusion 2
Made with engine (Sonic Worlds https://forums.sonicretro.org/index.php?threads/sonic-worlds-delta-1-5-2.35097/ )

Parameters
None

Game Link
https://gamejolt.com/games/satso/376344

SATFS

Specs
EXE Game
Cutscenes in engine
Made in Clickteam Fusion 2.5+
Made with engine (Core Framework https://github.com/nihil92/core )

Parameters
None

Game Link
https://stardropsmh.github.io/sonic-and-the-fallen-star/

**Comment by AITYunivers** [comment]
You're not actually telling us the issue. Sonic: After The Sequel decompiles fine. Sonic and the Fallen Star seems to have a compression issue but I still need both the errors you're getting.

**Comment by SuperSonic472** [comment]
SATSO

4810934
[12:55:00:13] Fusion Build: 292
Unhandled exception. Ionic.Zlib.ZlibException: Bad state (unknown compression method (0x9C))
   at Ionic.Zlib.InflateManager.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibCodec.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.ZlibStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.ZlibBaseStream.UncompressBuffer(Byte[] compressed, Stream decompressor)
   at Ionic.Zlib.ZlibStream.UncompressBuffer(Byte[] compressed)
   at CTFAK.Memory.Decompressor.DecompressBlock(ByteReader reader, Int32 size, Int32 decompSize) in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\Decompression.cs:line 30
   at CTFAK.Memory.Decryption.DecodeMode3(Byte[] chunkData, Int32 chunkSize, Int32 chunkId, Int32& decompressed) in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\Decryption.cs:line 92
   at CTFAK.CCN.Chunks.Chunk.Read() in E:\repos\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Chunk.cs:line 49
   at CTFAK.CCN.GameData.Read(ByteReader reader) in E:\repos\CTFAK2.0\Core\CTFAK.Core\CCN\GameData.cs:line 97
   at CTFAK.FileReaders.ExeFileReader.LoadGame(String gamePath) in E:\repos\CTFAK2.0\Core\CTFAK.Core\EXE\ExeFileReader.cs:line 72
   at Program.Main(String[] args) in E:\repos\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 123

SATFS

Unhandled exception. System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt16()
   at CTFAK.Memory.ByteReader.PeekUInt16() in E:\repos\CTFAK2.0\Core\CTFAK.Core\Memory\ByteReader.cs:line 65
   at CTFAK.FileReaders.ExeFileReader.ReadHeader(ByteReader reader) in E:\repos\CTFAK2.0\Core\CTFAK.Core\EXE\ExeFileReader.cs:line 83
   at CTFAK.FileReaders.ExeFileReader.LoadGame(String gamePath) in E:\repos\CTFAK2.0\Core\CTFAK.Core\EXE\ExeFileReader.cs:line 42
   at Program.Main(String[] args) in E:\repos\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 123

**Comment by SuperSonic472** [comment]
Idk if this works but bump

**Comment by yoann4d** [comment]
fnaf

**Comment by yoann4d** [comment]
fnaf fan made

**Comment by AITYunivers** [comment]
Attempted to fix this, was unable to. Weird decryption shit ruining everything.

**Comment by GreenyTF** [comment]
This because of encrypted chunks, if remove those chunks, another error appear when ctfak tries to read frames.
