### ISSUE TITLE
Dump as MFA fails with Int16 overflow

### ISSUE THREAD

**Issue by 000TragicSolitude** [CTFAK/CTFAK2.0#84]
Using on Bullet Requiem, a JP title.
All files seem to be read and processed correct, Dump Everything works without crash.
Thanks for being kind enough to handle non-Unicode stuff, guys. I appreciate it!

Snippet:
`[11:44:56:71] Translating frame 教団前イベント2 - 195
pos: 16
pos: 56
[11:45:04:01] System.OverflowException: Value was either too large or too small for an Int16.
   at System.Convert.ThrowInt16OverflowException()
   at CTFAK.MMFParser.EXE.Loaders.Events.Parameters.Group.generateChecksum(String name, String pass) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Group.cs:line 32
   at CTFAK.MMFParser.EXE.Loaders.Events.Parameters.Group.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Group.cs:line 71
   at CTFAK.CCN.Chunks.Frame.Parameter.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Events.cs:line 520
   at CTFAK.CCN.Chunks.Frame.Condition.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Events.cs:line 408
   at CTFAK.CCN.Chunks.Frame.EventGroup.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Events.cs:line 338
   at CTFAK.MFA.MFAEvents.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\MFA\MFAEvents.cs:line 203
   at CTFAK.MFA.MFAFrame.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\MFA\MFAFrame.cs:line 129
   at CTFAK.MFA.MFAData.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\MFA\MFAData.cs:line 285
   at CTFAK.Tools.FTDecompile.Execute(IFileReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Plugins\CTFAK.Decompiler\FTDecompile.cs:line 608
   at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 233`

Full log attached
[Latest.log](https://github.com/CTFAK/CTFAK2.0/files/13196527/Latest.log)

**Comment by AITYunivers** [comment]
@1987kostya1 fix your checksums :)

**Comment by PotatoMastah** [comment]
any fix for this? using the parameter -noimg made it finish without errors but still create a buggy file...
