### ISSUE TITLE
Dump as MFA fails with System.NullReferenceException

### ISSUE THREAD

**Issue by Aruvelut-123** [CTFAK/CTFAK2.0#86]
Using on Mr.TomatoS.
All files seem to be read and processed correct, Dump Everything works without crash.
Thanks for being kind enough to handle non-Unicode stuff, guys. I appreciate it!

Snippet:
`[18:42:22:93] Reading Fonts
[18:42:22:93] Reading Sounds
[18:42:22:93] Reading Music
[18:42:22:93] Reading Icons
[18:42:22:94] Reading Images
[18:42:22:95] Reading MFA Chunk 33 (Frame Virtual Rect)
[18:42:22:96] Reading MFA Chunk 37 (Layer Shader Settings)
[18:42:22:96] Reading MFA Chunk 40 (Frame Shader Settings)
[18:42:22:96] Reading MFA Chunk 39 (Frame Movement Timer)
[18:42:23:09] System.NullReferenceException: Object reference not set to an instance of an object.
   at CTFAK.Core.CCN.Chunks.Banks.ImageBank.FusionImage.FromBitmap(Bitmap bmp) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Banks\ImageBank\FusionImage.cs:line 139
   at CTFAK.Tools.FTDecompile.<Execute>g__TranslateObject|7_1(MFAData mfa, GameData game, ObjectInfo item, Boolean exyt) in D:\a\CTFAK2.0\CTFAK2.0\Plugins\CTFAK.Decompiler\FTDecompile.cs:line 851
   at CTFAK.Tools.FTDecompile.Execute(IFileReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Plugins\CTFAK.Decompiler\FTDecompile.cs:line 249
   at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 233`

**Comment by Aruvelut-123** [comment]
Using files that compiled by Github Actions
