### ISSUE TITLE
keep getting this error

### ISSUE THREAD

**Issue by idkwhyimherelmaoo** [CTFAK/CTFAK2.0#91]
System.DllNotFoundException
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'x64\zlibwapi.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at Joveler.DynLoader.NetSafeLibHandle..ctor(String libPath)
   at Joveler.DynLoader.DynLoaderBase.LoadLibrary(String libPath)
   at Joveler.DynLoader.LoadManagerBase`1.GlobalInit(String libPath)
   at Joveler.Compression.ZLib.ZLibInit.GlobalInit(String libPath)
   at CTFAK.CTFAKCore.Init() in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CTFAKCore.cs:line 27
   at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 29

**Comment by OWER396** [comment]
https://github.com/CTFAK/CTFAK2.0#installing-a-precompiled-artifact
